name: whiteboard
description: A package for freehand use on whiteboard. This package provides a cross platform widget for drawing with controller.
version: 1.0.0
homepage: https://github.com/rkishan516/whiteboard

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4